# Generated by Django 5.0.3 on 2024-03-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=55)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('atualizacao', models.DateField(auto_now_add=True)),
                ('concluida', models.BooleanField(default=1)),
            ],
        ),
    ]
