# Generated by Django 5.0.3 on 2024-03-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListApp', '0002_alter_tarefa_atualizacao_alter_tarefa_data_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='atualizacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_concluido',
            field=models.DateField(null=True),
        ),
    ]
