# Generated by Django 5.0.3 on 2024-03-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListApp', '0003_alter_tarefa_atualizacao_alter_tarefa_data_concluido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='atualizacao',
        ),
    ]
