# Generated by Django 5.0.6 on 2024-06-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListApp', '0004_remove_tarefa_atualizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_concluido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
